{application,dealcloud,
             [{applications,[kernel,stdlib,elixir,logger,httpoison,hackney,
                             poison,json]},
              {description,"dealcloud"},
              {modules,['Elixir.Dealcloud','Elixir.Dealcloud 2',
                        'Elixir.Dealcloud.Auth','Elixir.Dealcloud.Auth 2',
                        'Elixir.Dealcloud.Data','Elixir.Dealcloud.Data 2',
                        'Elixir.Dealcloud.Data.Entries',
                        'Elixir.Dealcloud.Data.Entries 2',
                        'Elixir.Dealcloud.Data.EntryData',
                        'Elixir.Dealcloud.Data.EntryData 2',
                        'Elixir.Dealcloud.Data.Filter',
                        'Elixir.Dealcloud.Data.Filter 2',
                        'Elixir.Dealcloud.Data.Merge',
                        'Elixir.Dealcloud.Data.Merge 2',
                        'Elixir.Dealcloud.Data.PostQuery',
                        'Elixir.Dealcloud.Data.PostQuery 2',
                        'Elixir.Dealcloud.Data.Query',
                        'Elixir.Dealcloud.Data.Query 2',
                        'Elixir.Dealcloud.Data.Record',
                        'Elixir.Dealcloud.Data.Record 2',
                        'Elixir.Dealcloud.Data.ViewFilter',
                        'Elixir.Dealcloud.Data.ViewFilter 2',
                        'Elixir.Dealcloud.HistorQuery',
                        'Elixir.Dealcloud.HistorQuery 2',
                        'Elixir.Dealcloud.Impl','Elixir.Dealcloud.Impl 2',
                        'Elixir.Dealcloud.Impl.Auth',
                        'Elixir.Dealcloud.Impl.Auth 2',
                        'Elixir.Dealcloud.Impl.Data',
                        'Elixir.Dealcloud.Impl.Data 2',
                        'Elixir.Dealcloud.Impl.Data.EntryData',
                        'Elixir.Dealcloud.Impl.Data.EntryData 2',
                        'Elixir.Dealcloud.Impl.Data.EntryType',
                        'Elixir.Dealcloud.Impl.Data.EntryType 2',
                        'Elixir.Dealcloud.Impl.Data.History',
                        'Elixir.Dealcloud.Impl.Data.History 2',
                        'Elixir.Dealcloud.Impl.Data.Merge',
                        'Elixir.Dealcloud.Impl.Data.Merge 2',
                        'Elixir.Dealcloud.Impl.Data.RowData',
                        'Elixir.Dealcloud.Impl.Data.RowData 2',
                        'Elixir.Dealcloud.Impl.Data.View',
                        'Elixir.Dealcloud.Impl.Data.View 2',
                        'Elixir.Dealcloud.Impl.Management',
                        'Elixir.Dealcloud.Impl.Management 2',
                        'Elixir.Dealcloud.Impl.Management.Activity',
                        'Elixir.Dealcloud.Impl.Management.Activity 2',
                        'Elixir.Dealcloud.Impl.Management.Group',
                        'Elixir.Dealcloud.Impl.Management.Group 2',
                        'Elixir.Dealcloud.Impl.Management.License',
                        'Elixir.Dealcloud.Impl.Management.License 2',
                        'Elixir.Dealcloud.Impl.Management.Proxy',
                        'Elixir.Dealcloud.Impl.Management.Proxy 2',
                        'Elixir.Dealcloud.Impl.Management.User',
                        'Elixir.Dealcloud.Impl.Management.User 2',
                        'Elixir.Dealcloud.Impl.Schema',
                        'Elixir.Dealcloud.Impl.Schema 2',
                        'Elixir.Dealcloud.Impl.Schema.AllFields',
                        'Elixir.Dealcloud.Impl.Schema.AllFields 2',
                        'Elixir.Dealcloud.Impl.Schema.ChoiceFieldValues',
                        'Elixir.Dealcloud.Impl.Schema.ChoiceFieldValues 2',
                        'Elixir.Dealcloud.Impl.Schema.Currencies',
                        'Elixir.Dealcloud.Impl.Schema.Currencies 2',
                        'Elixir.Dealcloud.Impl.Schema.EntryTypes',
                        'Elixir.Dealcloud.Impl.Schema.EntryTypes 2',
                        'Elixir.Dealcloud.Impl.Schema.FieldTypes',
                        'Elixir.Dealcloud.Impl.Schema.FieldTypes 2',
                        'Elixir.Dealcloud.Impl.Schema.Fields',
                        'Elixir.Dealcloud.Impl.Schema.Fields 2',
                        'Elixir.Dealcloud.Impl.Schema.FilterOperations',
                        'Elixir.Dealcloud.Impl.Schema.FilterOperations 2',
                        'Elixir.Dealcloud.Impl.Schema.SystemFieldTypes',
                        'Elixir.Dealcloud.Impl.Schema.SystemFieldTypes 2',
                        'Elixir.Dealcloud.Impl.Schema.TimeZones',
                        'Elixir.Dealcloud.Impl.Schema.TimeZones 2',
                        'Elixir.Dealcloud.Impl.Schema.Users',
                        'Elixir.Dealcloud.Impl.Schema.Users 2',
                        'Elixir.Dealcloud.Management',
                        'Elixir.Dealcloud.Management 2',
                        'Elixir.Dealcloud.Management.ActivityQuery',
                        'Elixir.Dealcloud.Management.ActivityQuery 2',
                        'Elixir.Dealcloud.Management.Proxy',
                        'Elixir.Dealcloud.Management.Proxy 2',
                        'Elixir.Dealcloud.Management.ProxyQuery',
                        'Elixir.Dealcloud.Management.ProxyQuery 2',
                        'Elixir.Dealcloud.Management.User',
                        'Elixir.Dealcloud.Management.User 2',
                        'Elixir.Dealcloud.Management.UserLicense',
                        'Elixir.Dealcloud.Management.UserLicense 2',
                        'Elixir.Dealcloud.Management.UserQuery',
                        'Elixir.Dealcloud.Management.UserQuery 2',
                        'Elixir.Dealcloud.Schema','Elixir.Dealcloud.Schema 2',
                        'Elixir.Dealcloud.Schema.SystemEntryTypes',
                        'Elixir.Dealcloud.Schema.SystemEntryTypes 2']},
              {registered,[]},
              {vsn,"0.1.0"}]}.
